name: livecd
on: workflow_dispatch
#workflow_dispatch
#[push]
jobs:
  command:
    name: Use Linux commands
    runs-on: ubuntu-24.04-arm
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        run: |
          ####################### Set ##############
          export u_boot_defconfig="orangepi-5-plus-rk3588_defconfig"
          export fdt_deb="rk3588-orangepi-5-plus"
          export board="orangepi-5-plus"
          #########################################
          mkdir  build

      - name: Show ubuntu details
        run: |        
          sudo apt update
          sudo apt install -y build-essential gcc-aarch64-linux-gnu devscripts dctrl-tools   \
          qemu-user-static qemu-system-arm qemu-efi-aarch64 u-boot-tools binfmt-support      \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted            \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python3 dctrl-tools      \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools         \
          python3-distutils-extra python3-pkg-resources swig libfdt-dev libpython3-dev bison \
          livecd-rootfs

      - name: u-boot
        run: |
          mkdir arm64
          sudo mount -t tmpfs -o size=1G tmpfs arm64
          cd arm64
          git clone --depth 1 https://github.com/rockchip-linux/rkbin
          DDR=`ls rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz*.bin`
          BL31=`ls rkbin/bin/rk35/rk3588_bl31*.elf`
          git clone --depth 1 https://github.com/u-boot/u-boot.git -b v2025.01
          cd u-boot
          if [ ! -f configs/$u_boot_defconfig ]; then
            echo "$u_boot_defconfig not found in configs"
            cd ..
            exit 1
          fi
          sed -i 's/scsi //' include/configs/rockchip-common.h
          sed -i 's/mmc1/scsi mmc1/' include/configs/rockchip-common.h
          sed -i 's/#ifndef CONFIG_XPL_BUILD/#ifndef CONFIG_XPL_BUILD\n\n# define BOOT_TARGET_DEVICES_SCSI(func)  func(SCSI, scsi, 0, 0, 1) func(SCSI, scsi, 0, 0, 2)/' include/configs/rockchip-common.h
          make $u_boot_defconfig && make
          cp u-boot-rockchip.bin ../../build/
          sudo umount arm64

      - name: livecd-build
        run: |
          sudo /bin/bash livecd-build

      - name: Upload a kernel
        uses: actions/upload-artifact@v4.5.0
        with:
        # A file, directory or wildcard pattern that describes what to upload
          name: ubuntu
          path: image/*.img
          compression-level: 0
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
